name: intake_omnisci

channels:
  - conda-forge

dependencies:
  - intake>=0.5.3
  - pandas<0.26
  - pip
  - pymapd=0.24
  - pytest
  - python>=3.7
  - rever
  - ibis-framework

  - pip:
    - "-e ."
